### ISSUE TITLE
Latest version constantly crashes on boot

### ISSUE THREAD

**Issue by SilentDave75** [yak3d/StarfieldVoiceTool#25] opened 2024-12-30 02:06 UTC
I've been trying to get the latest update to run since it came out, but it always crashes. The cmd screen comes up, says the usual "times have changes" twice, then spits out a bunch of errors. I've deleted the cache.json fille as recommended on Nexus, and it still won't work.
[starfieldvt20241229.log](https://github.com/user-attachments/files/18271552/starfieldvt20241229.log)
This is the log file. It references a non-existent folder on my D drive. Maybe that's the issue?

**Comment by yak3d** [comment] 2024-12-30 02:19
Thanks for the log file. It seems specifically related to:
```
 ---> Mutagen.Bethesda.Plugins.Exceptions.MissingModMappingException: Master flag lookup was not provided.
 ```

Couple questions, and a warning I may need to follow up with the Mutagen folks about this.

1. Where is your game located?
2. Are you running Starfield Voice Tool via a Mod Manager?
3. Do you normally manage your mods in a Mod Manager?

w.r.t. the D drive, I think that's just from the debugging info and I don't believe is the cause of any issues.

**Comment by SilentDave75** [comment] 2024-12-30 02:22
1. Steam default directory
2. No. I wasn't aware I could
3. Yes

**Comment by SilentDave75** [comment] 2024-12-30 02:29
Ok, I launched it successfully using Mod Organizer 2. Weird, because the first release worked just fine without MO2.

**Comment by yak3d** [comment] 2024-12-30 02:31
This is just a hunch, but I'm wondering if there's masters in your `Plugins.txt` that depend on other masters and those aren't loaded?

**Comment by SilentDave75** [comment] 2024-12-30 02:33
I don't use plugins.txt. From my understanding, it was rendered unnecessary when the creation kit was released, iirc.

**Comment by yak3d** [comment] 2024-12-30 02:37
The SFSE plugin was made unnecessary but the game still uses the file itself. The plugin is no longer necessary because the game now reads that file. It's usually located at `%LOCALAPPDATA%\Starfield`. Might be worth checking it outside of MO2 or just making sure there is one. That's the biggest difference between running in and out of MO2.

The only other thing I can think of is, if you use it, RootBuilder can replace game files with older versions sometimes and maybe that's causing an issue that MO2 "fixes" since it will have RootBuilder dump in the newer files.

**Comment by yak3d** [comment] 2024-12-31 20:50
I'm going to close this for now but let me know if you still encounter issues.

**Closed as not planned by yak3d** 2024-12-31 20:50 UTC

**Comment by SilentDave75** [comment] 2024-12-31 21:52
It's been working fine since I started opening it in MO2. Thanks.
